version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    networks:
      - ecommerce-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net
    depends_on:
      - postgres

networks:
  ecommerce-net:
    name: ecommerce-net
    driver: bridge

volumes:
  postgres_data: