version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    networks:
      - ecommerce-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: golang:1.24-alpine
    container_name: ecommerce-app
    volumes:
      - .:/app  # 映射当前目录到容器的 /app 目录
    working_dir: /app  # 设置工作目录为 /app
    ports:
      - "8080:8080"
    environment:
      - GOPROXY=https://goproxy.cn  # 设置 Go 代理
    networks:
      - ecommerce-net
    depends_on:
      - postgres
    command: sh -c "go run main.go"  # 启动命令

networks:
  ecommerce-net:
    name: ecommerce-net
    driver: bridge

volumes:
  postgres_data: